-- ============================================================
-- Saudi Opportunity Hub — Pipeline Run: 2026-05-21
-- 14 verified opportunities (passed all 3 agents)
-- Excluded from investsaudi.sa: none proposed
-- Sector corrections at final check: 0
-- ============================================================

INSERT INTO opportunities (
  title, sponsor_institution, country, sector, type, status,
  funding_amount, deadline, application_link, description_short,
  last_verified, eligibility_region
) VALUES
(
  'TAQADAM Startup Accelerator – KAUST & SABB',
  'King Abdullah University of Science and Technology (KAUST)',
  'Saudi Arabia',
  'Innovation & Entrepreneurship',
  'Accelerator',
  'Open',
  '$40,000 (up to $100,000 follow-on for top 10 startups)',
  NULL,
  'https://taqadam.kaust.edu.sa/',
  'A 6-month global startup accelerator powered by KAUST and SABB providing funding, mentorship, and network access to entrepreneurs aiming to scale in Saudi Arabia. International startups must have a realistic plan to expand to Saudi within one year.',
  '2026-05-21',
  'Global'
),
(
  'Sanabil Accelerator by 500 Global – Batch 11',
  '500 Global / Sanabil Investments (PIF)',
  'Saudi Arabia',
  'Innovation & Entrepreneurship',
  'Accelerator',
  'Open',
  'USD $100,000+ equity investment per startup',
  NULL,
  'https://500.co/founders/mena/seed-accelerator',
  'A 12-week growth-focused accelerator for tech startups with early traction in MENA, backed by 500 Global and Sanabil Investments (a PIF subsidiary). Provides equity investment, expert workshops, and access to a regional and global network.',
  '2026-05-21',
  'MENA'
),
(
  'SIDF Tanafusiya Program – Industry 4.0 & Energy Efficiency Financing',
  'Saudi Industrial Development Fund (SIDF)',
  'Saudi Arabia',
  'Industrial & Manufacturing',
  'Loan',
  'Open',
  'Financing up to 75% of project cost; financial incentives up to 25% of project cost',
  NULL,
  'https://www.sidf.gov.sa/FinancialSolutions/Incentive-Programs/Tanafusiya',
  'A specialized financing and incentive program for Saudi factories adopting automation, digitization, and energy efficiency (Industry 4.0) solutions. Offers a minimum 7-year tenor, up to 24-month grace period, and fast 8-week processing.',
  '2026-05-21',
  'Saudi Arabia'
),
(
  'SDB Excellence Financing for New Enterprises',
  'Social Development Bank (SDB)',
  'Saudi Arabia',
  'Private Sector',
  'Loan',
  'Open',
  'Up to SAR 4,000,000',
  NULL,
  'https://www.sdb.gov.sa/en/facilities-financing/excellence-financing',
  'A fully digital financing product supporting promising new Saudi enterprises (under 3 years old) with innovative or technical projects. Offers up to SAR 4 million, a 2-year grace period, and an 8-year repayment schedule with no branch visit required.',
  '2026-05-21',
  'Saudi Arabia'
),
(
  'Kafalah SME Loan Guarantee Program',
  'Kafalah Program / SME Bank (National Development Fund)',
  'Saudi Arabia',
  'Financial Services',
  'Loan Guarantee',
  'Open',
  'Loan guarantees from SAR 2.5 million to SAR 15 million (up to 80% guarantee)',
  NULL,
  'https://www.kafalah.gov.sa/en/Pages/default.aspx',
  'A government-backed SME loan guarantee program enabling micro, small, and medium enterprises to access bank financing without collateral. Kafalah guarantees up to 80% of the loan and is targeting SAR 20-22 billion in guarantees over 2025-2026.',
  '2026-05-21',
  'Saudi Arabia'
),
(
  'Saudi SME Bank – Working Capital & Term Loans',
  'SME Bank (National Development Fund)',
  'Saudi Arabia',
  'Private Sector',
  'Loan',
  'Open',
  'SAR 500,000 (Microloan) to SAR 15,000,000 (Working Capital / Term Loan)',
  NULL,
  'https://smebank.gov.sa/en/programs',
  'Saudi Arabia''s dedicated SME Bank offers a suite of financing products including microloans, working capital loans, e-commerce loans, and revolving credit facilities through an online portal. The bank has allocated SAR 10.5 billion to support SMEs.',
  '2026-05-21',
  'Saudi Arabia'
),
(
  'RDIA Saudi Innovation Grants Program (SIGP)',
  'Research, Development and Innovation Authority (RDIA)',
  'Saudi Arabia',
  'Innovation & Entrepreneurship',
  'Grant',
  'Open',
  'Varies by phase (Proof of Concept and Proof of Value phases)',
  NULL,
  'https://saudiminds.rdia.gov.sa/account/sigp-about',
  'A program by RDIA and NTDP empowering startups, SMEs, and entrepreneurs to transform ideas into innovative solutions addressing national challenges in Health, Sustainability, Energy, and Future Economies. Features a two-phase structure from concept to prototype.',
  '2026-05-21',
  'Saudi Arabia'
),
(
  'RDIA Technology Development Grant (TDG)',
  'Research, Development and Innovation Authority (RDIA)',
  'Saudi Arabia',
  'ICT',
  'Grant',
  'Open',
  'Varies (multi-year grants aligned with national R&D priorities)',
  NULL,
  'https://saudiminds.rdia.gov.sa/account/grants-info/4?nationalPrioritiesId=1',
  'A competitive grant bridging the gap between research and commercialization for technology projects addressing Saudi Arabia''s national R&D priorities. Part of the Saudi Applied Research and Technology Initiative via the SaudiMinds portal.',
  '2026-05-21',
  'Saudi Arabia'
),
(
  'Tourism Development Fund (TDF) – NBFI Finance Companies Program',
  'Tourism Development Fund (TDF)',
  'Saudi Arabia',
  'Tourism & Quality of Life',
  'Loan',
  'Open',
  'Varies (USD 4B fund; tailored for micro, small, and medium tourism enterprises)',
  NULL,
  'https://www.tdf.gov.sa/en/programs/finance-companies-program/',
  'A TDF program with licensed financing companies providing working capital and capex financing to micro, small, and medium enterprises in Saudi Arabia''s tourism sector. Supports the goal of raising tourism''s GDP contribution to 10% by 2030.',
  '2026-05-21',
  'Saudi Arabia'
),
(
  'Google for Startups Accelerator – Middle East, North Africa & Turkey (MENAT)',
  'Google',
  'United Arab Emirates',
  'ICT',
  'Accelerator',
  'Open',
  'Equity-free; access to Google resources, technical expertise, and $500,000+ in partner deals',
  NULL,
  'https://startup.google.com/programs/accelerator/middle-east-north-africa-turkey/',
  'A hybrid accelerator for 10-15 growth-stage tech startups from MENA, Turkey, and Central Asia offering equity-free support, AI/ML expertise, 1:1 mentoring, and a global investor network. Focused on deeply technical startups using AI and machine learning.',
  '2026-05-21',
  'MENA'
),
(
  'Oxagon KSA Accelerator – NEOM Advanced Manufacturing',
  'NEOM / Oxagon',
  'Saudi Arabia',
  'Industrial & Manufacturing',
  'Accelerator',
  'Open',
  'Access to investment, piloting, and enterprise partnerships (ticket varies)',
  NULL,
  'https://www.neom.com/en-us/regions/oxagon/oxagon-accelerator/ksa-accelerator',
  'A 12-week accelerator for Saudi startups in advanced manufacturing, clean tech, IoT, and robotics within NEOM''s Oxagon industrial zone. Provides mentorship, investor access (100+ VCs across MENA), and piloting opportunities with major corporates.',
  '2026-05-21',
  'Saudi Arabia'
),
(
  'Flat6Labs Riyadh Seed Program',
  'Flat6Labs / National Technology Development Program (NTDP)',
  'Saudi Arabia',
  'Innovation & Entrepreneurship',
  'Accelerator',
  'Open',
  'SAR 500,000 cash investment per startup',
  NULL,
  'https://flat6labs.com/program/riyadh-seed-program-page/',
  'A 4-month seed accelerator program in Riyadh investing in 20+ Saudi startups annually with SAR 500,000 in cash, strategic mentorship, legal support, office space, and investor network access. Supported by the National Technology Development Program.',
  '2026-05-21',
  'Saudi Arabia'
),
(
  'Saudi Environment Fund – Incentives and Grants Program',
  'Saudi Environment Fund',
  'Saudi Arabia',
  'Environment Services',
  'Grant',
  'Open',
  'Varies by project type (environment sector incentives and grants)',
  NULL,
  'https://www.ef.gov.sa/en/programs',
  'A national program providing grants and incentives to businesses, NGOs, and research institutions to promote environmentally friendly practices across waste management, wildlife conservation, vegetation, and Green Factory manufacturing improvements.',
  '2026-05-21',
  'Saudi Arabia'
),
(
  'HRDF Employment Support Program for Private Sector Establishments',
  'Human Resources Development Fund (HRDF / Hadaf)',
  'Saudi Arabia',
  'Private Sector',
  'Grant',
  'Open',
  '30% of employee salary for 2 years, up to SAR 3,000/month per hire',
  NULL,
  'https://www.hrdf.org.sa/en/products-and-services/programs/establishments/enable/employment-support/',
  'A subsidy program for private sector businesses hiring Saudi nationals, covering 30% of the employee''s salary for the first two years (up to SAR 3,000/month). Supports business growth and Saudization goals across all private sector industries.',
  '2026-05-21',
  'Saudi Arabia'
)
ON CONFLICT (application_link) DO NOTHING;
