-- Seed: 20 new verified investment opportunities (SA-N1715 through SA-N1734)
-- Pipeline: 4-agent verification (URL liveness, validity, accuracy, dedup)
-- All application_links confirmed NOT in DB prior to insert (2026-05-26)
-- Sectors use canonical 17-value taxonomy

INSERT INTO opportunities (
  id, title, description_short, type, sponsor_institution, country,
  eligibility_region, eligibility_entities, funding_amount, funding_type,
  application_link, deadline_date, status, language, notes,
  last_verified, sectors, "isNew", profiles
) VALUES

('SA-N1715', 'Tech Champions 6',
 'MCIT 6th-cohort AI-focused incubator for Saudi startups, offering equity investment up to SAR 150,000 per startup with a total programme pool of SAR 6,000,000 across 40 startups.',
 'accelerator', 'Ministry of Communications and Information Technology (MCIT)',
 'Saudi Arabia', 'Saudi_only', 'startups, entrepreneurs',
 'Up to SAR 150,000 per startup; total pool SAR 6,000,000', 'equity',
 'https://code.mcit.gov.sa/en/tech-champions-6',
 NULL, 'open', 'en', 'Sixth edition of the annual MCIT Tech Champions AI incubator.',
 '2026-05-26', ARRAY['ICT'], true, ARRAY['startup']),

('SA-N1716', 'Entertainment Activities Accelerator',
 'General Entertainment Authority 3rd-edition accelerator supporting entertainment entrepreneurs and businesses seeking to enter and grow in Saudi Arabia under Vision 2030.',
 'accelerator', 'General Entertainment Authority (GEA)',
 'Saudi Arabia', 'Saudi_only', 'startups, entrepreneurs, businesses',
 'Not publicly specified', 'other',
 'https://gea.gov.sa/en/entertainment-activities/',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Tourism & Quality of Life'], true, ARRAY['startup', 'business']),

('SA-N1717', 'GEA Entertainment Lab',
 'GEA creative innovation challenge for entertainment sector startups running through December 2026, with prizes up to SAR 300,000 and a support package exceeding USD 1,000,000.',
 'competition', 'General Entertainment Authority (GEA)',
 'Saudi Arabia', 'Saudi_only', 'startups, entrepreneurs, creatives',
 'Up to SAR 300,000; support package USD 1,000,000+', 'grant',
 'https://gea.gov.sa/en/initiatives/entertainment-lab/',
 '2026-12-31', 'open', 'en', NULL,
 '2026-05-26', ARRAY['Tourism & Quality of Life'], true, ARRAY['startup']),

('SA-N1718', 'GEA Entertainment Innovations Program',
 'GEA programme supporting innovations in the entertainment sector with prizes exceeding SAR 300,000 and a total support package valued at over USD 1,000,000.',
 'competition', 'General Entertainment Authority (GEA)',
 'Saudi Arabia', 'Saudi_only', 'startups, entrepreneurs',
 'Prizes SAR 300,000+; support package USD 1,000,000+', 'grant',
 'https://gea.gov.sa/en/media-center/news/entertainment-innovations/',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Tourism & Quality of Life'], true, ARRAY['startup']),

('SA-N1719', 'Women Entrepreneurs Empowerment Program',
 'Monshaat programme empowering Saudi women entrepreneurs through capacity building, networking, and access to financing — female business ownership reached 42% in 2024.',
 'program', 'General Authority for Small and Medium Enterprises (Monshaat)',
 'Saudi Arabia', 'Saudi_only', 'women entrepreneurs, startups, SMEs',
 'Not publicly specified', 'other',
 'https://www.monshaat.gov.sa/en/node/13570',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Private Sector'], true, ARRAY['startup', 'sme']),

('SA-N1720', 'Khalifa Fund Funding Scheme',
 'Interest-free SME loans and micro-financing from the Abu Dhabi government Khalifa Fund for Enterprise Development, ranging from AED 150,000 to AED 3,000,000.',
 'financing', 'Khalifa Fund for Enterprise Development',
 'UAE', 'Global_including_Saudi', 'entrepreneurs, SMEs, startups',
 'AED 150,000 – AED 3,000,000 (interest-free)', 'loan',
 'https://www.khalifafund.ae/services/funding-scheme/',
 NULL, 'open', 'en', 'Abu Dhabi government body; GCC-region coverage.',
 '2026-05-26', ARRAY['Financial Services'], true, ARRAY['startup', 'sme']),

('SA-N1721', 'Founder Institute Riyadh Startup Accelerator',
 'Global pre-seed startup accelerator operating in Riyadh as the 35th Founder Institute chapter, providing mentorship, equity-based support, and access to an 8,200+ mentor global network.',
 'accelerator', 'Founder Institute',
 'Saudi Arabia', 'Saudi_only', 'founders, startups, entrepreneurs',
 'Equity-based; no upfront cost', 'equity',
 'https://fi.co/apply/13308',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Innovation & Entrepreneurship'], true, ARRAY['startup', 'founder']),

('SA-N1722', 'Saudi Pharma & Biotech Network Programs',
 'SPB Network programmes for pharma and biotech entrepreneurs in Saudi Arabia, including mentorship, innovation events, and sector networking for professionals and startups.',
 'program', 'Saudi Pharma & Biotech Network (SPB Network)',
 'Saudi Arabia', 'Saudi_only', 'startups, researchers, pharma professionals',
 'Not publicly specified', 'other',
 'https://www.saudipb.org/en',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Pharma & Biotech'], true, ARRAY['startup', 'researcher']),

('SA-N1723', 'Tamkeen Digital Enablement Program',
 'Bahrain Labour Fund subsidises 50–60% of digital transformation project costs for SMEs through approved technology service providers, launched Q4 2025.',
 'subsidy', 'Labour Fund (Tamkeen)',
 'Bahrain', 'Global_including_Saudi', 'SMEs, businesses',
 'Up to 60% of project cost (enterprises cover 40–50%)', 'subsidy',
 'https://www.tamkeen.bh/en/programs/digital-enablement-program/',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['ICT'], true, ARRAY['sme', 'business']),

('SA-N1724', 'SABIC Home of Innovation',
 'SABIC global innovation platform connecting 42+ partner companies for collaborative research, co-investment, and industrial partnerships in chemicals and advanced materials.',
 'program', 'SABIC',
 'Saudi Arabia', 'Global_including_Saudi', 'companies, startups, innovators',
 'Not publicly specified; partnership-based', 'other',
 'https://www.sabic.com/en/hoi',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Chemicals'], true, ARRAY['startup', 'business']),

('SA-N1725', 'Monshaat SME Programs Hub',
 'Central portal for all Monshaat programmes supporting Saudi SMEs, including accelerators, financing, mentoring, and women entrepreneurship initiatives across multiple sectors.',
 'program', 'General Authority for Small and Medium Enterprises (Monshaat)',
 'Saudi Arabia', 'Saudi_only', 'SMEs, startups, entrepreneurs',
 'Multiple programmes with varying support', 'mixed',
 'https://monshaat.gov.sa/en/programs',
 NULL, 'open', 'en', 'Hub page listing all Monshaat active programmes.',
 '2026-05-26', ARRAY['Private Sector'], true, ARRAY['startup', 'sme']),

('SA-N1726', 'PIF Transport and Logistics Investment Opportunities',
 'Public Investment Fund private-sector partnership opportunities across transport and logistics, with 16 active investment openings and total sector investments exceeding SAR 250 billion.',
 'investment', 'Public Investment Fund (PIF)',
 'Saudi Arabia', 'Global_including_Saudi', 'companies, investors, developers',
 'Multiple investment opportunities; sector total SAR 250,000,000,000+', 'equity',
 'https://www.pif.gov.sa/en/private-sector-hub/explore-opportunities/transport-and-logistics/',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Transport & Logistics'], true, ARRAY['business', 'investor']),

('SA-N1727', 'Ministry of Industry and Mineral Resources — Industry Sector Investment',
 'Saudi MIM Standard Incentives Programme for the industrial sector (SAR 10B pool, January 2025) providing grants, concessions, and investment services for manufacturing projects.',
 'investment', 'Ministry of Industry and Mineral Resources (MIM)',
 'Saudi Arabia', 'Saudi_only', 'manufacturers, investors, companies',
 'SAR 10,000,000,000 Standard Incentives pool', 'grant',
 'https://mim.gov.sa/en/sectors/industry',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Industrial & Manufacturing'], true, ARRAY['business', 'investor']),

('SA-N1728', 'IMPACT46 Programs',
 'IMPACT46 CMA-authorised Saudi VC programmes including Fund III (SAR 500M) and Gaming Fund (SAR 150M) for Saudi startups seeking growth-stage equity financing.',
 'financing', 'IMPACT46',
 'Saudi Arabia', 'Saudi_only', 'startups, growth-stage companies',
 'Fund III: SAR 500,000,000; Gaming Fund: SAR 150,000,000', 'equity',
 'https://impact46.sa/programs',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Innovation & Entrepreneurship'], true, ARRAY['startup']),

('SA-N1729', 'Jadeer Service — Monshaat SME Qualification Program',
 'Monshaat qualification and certification service for Saudi SMEs granting eligibility recognition and up to 20% financing fee discounts through partner financial institutions.',
 'program', 'General Authority for Small and Medium Enterprises (Monshaat)',
 'Saudi Arabia', 'Saudi_only', 'SMEs',
 'Up to 20% discount on financing fees through partner institutions', 'subsidy',
 'https://monshaat.gov.sa/en/node/12778',
 NULL, 'open', 'en', 'Jadeer is Monshaat''s official SME qualification and certification programme.',
 '2026-05-26', ARRAY['Private Sector'], true, ARRAY['sme']),

('SA-N1730', 'Royal Commission for Jubail and Yanbu — Industrial Investor Services',
 'RCJY industrial investor services across four industrial cities (Jubail, Yanbu, Ras Al-Khair, Jazan) for manufacturing, logistics, and industrial development project establishment.',
 'investment', 'Royal Commission for Jubail and Yanbu (RCJY)',
 'Saudi Arabia', 'Global_including_Saudi', 'manufacturers, investors, industrial companies',
 'Not specified; varies by investment type and industrial city', 'other',
 'https://www.rcjy.gov.sa/en/services',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Industrial & Manufacturing'], true, ARRAY['business', 'investor']),

('SA-N1731', 'Saudi Business Center — Business Registration and Investment Services',
 'Saudi government unified business services platform for commercial registration, licensing, and business setup, including expanded Special Economic Zone services active in 2026.',
 'other', 'Saudi Business Center (SBC)',
 'Saudi Arabia', 'Saudi_only', 'businesses, investors, entrepreneurs',
 'Not applicable — regulatory services', 'other',
 'https://business.sa',
 NULL, 'open', 'en', 'Official SBC domain is business.sa (Ministry of Commerce).',
 '2026-05-26', ARRAY['Private Sector'], true, NULL),

('SA-N1732', 'Agricultural Development Fund — Credit and Loan Programs',
 'Saudi ADF provides agricultural credit and loans covering up to 70% of agri-tech project value, with SAR 7.5 billion+ approved for agri-tech and food-sector modernisation in 2025.',
 'financing', 'Agricultural Development Fund (ADF)',
 'Saudi Arabia', 'Saudi_only', 'agri-tech startups, farmers, food companies',
 'Up to 70% of project value; SAR 7,500,000,000+ total in 2025', 'loan',
 'https://adf.gov.sa/en/CreditServices/Loans/Pages/default.aspx',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Agriculture & Food Processing'], true, ARRAY['startup', 'sme', 'business']),

('SA-N1733', 'Saudi Health Innovation Hub Programs',
 'Saudi Health Innovation Hub (HIH) supports healthtech startups and innovators in Saudi Arabia through accelerator programmes, validation support, and market access partnerships.',
 'accelerator', 'Health Innovation Hub (HIH)',
 'Saudi Arabia', 'Saudi_only', 'healthtech startups, medical innovators',
 'Not publicly specified', 'other',
 'https://hih.com.sa',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Healthcare & Life Sciences'], true, ARRAY['startup', 'researcher']),

('SA-N1734', 'NEOM Investment Opportunities',
 'Investment and development partnership opportunities in NEOM, Saudi Arabia''s SAR 1.5 trillion futuristic development encompassing The Line, Sindalah, OXAGON, and NEOM Bay.',
 'investment', 'NEOM',
 'Saudi Arabia', 'Global_including_Saudi', 'investors, developers, companies',
 'Multiple investment tracks; total NEOM budget SAR 1,500,000,000,000', 'equity',
 'https://neom.com/en-gb/investment',
 NULL, 'open', 'en', NULL,
 '2026-05-26', ARRAY['Real Estate'], true, ARRAY['investor', 'business']);
