INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Saudi Environment Fund – Environmental Grants & Incentives Program', 'Saudi Environment Fund', 'Saudi Arabia', ARRAY['Environment Services'], 'Grant', 'open', NULL, 'open', 'https://www.ef.gov.sa/en/incentives', 'Saudi Environment Fund grants and incentives for environmental projects and green economy initiatives in Saudi Arabia.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://www.ef.gov.sa/en/incentives');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'SAMA FinTech Regulatory Sandbox', 'Saudi Central Bank (SAMA)', 'Saudi Arabia', ARRAY['Financial Services'], 'Regulatory Program', 'open', NULL, 'open', 'https://www.sama.gov.sa/en-US/RegulatoryS_andbox/Pages/default.aspx', 'Saudi Central Bank regulatory sandbox enabling FinTech companies to test innovative financial products and services in a controlled environment on a rolling basis.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://www.sama.gov.sa/en-US/RegulatoryS_andbox/Pages/default.aspx');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Saudi Data and AI Authority (SDAIA) – National AI Strategy & Initiatives', 'Saudi Data and Artificial Intelligence Authority (SDAIA)', 'Saudi Arabia', ARRAY['ICT'], 'Program', 'open', NULL, 'open', 'https://sdaia.gov.sa/en/SDAIA/SdaiaStrategies/Pages/default.aspx', 'SDAIA''s national AI and data strategy initiatives supporting Saudi Arabia''s AI ecosystem, workforce development, and digital transformation under Vision 2030 and the Year of AI 2026.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://sdaia.gov.sa/en/SDAIA/SdaiaStrategies/Pages/default.aspx');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Special Economic Zones Investment Program – ECZA', 'Economic Cities and Special Zones Authority (ECZA)', 'Saudi Arabia', ARRAY['Industrial & Manufacturing'], 'Investment Incentive', 'open', NULL, 'open', 'https://ecza.gov.sa/en/about-ecza', 'ECZA Special Economic Zones offering tax incentives, streamlined licensing, and investment opportunities across Saudi Arabia''s designated economic zones under the 2026 regulatory framework.', '2026-05-17'::date, 'Global'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://ecza.gov.sa/en/about-ecza');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'King Abdulaziz University Research Funding & Support Program', 'King Abdulaziz University (KAU)', 'Saudi Arabia', ARRAY['Education'], 'Research Grant', 'open', NULL, 'open', 'https://www.kau.edu.sa/en/page/funding-and-support-for-scientific-research', 'Research funding and support programs at King Abdulaziz University for scientific research projects, open to faculty, researchers, and collaborators aligned with Vision 2030.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://www.kau.edu.sa/en/page/funding-and-support-for-scientific-research');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Public Investment Fund (PIF) – Ventures & Strategic Investments', 'Public Investment Fund (PIF)', 'Saudi Arabia', ARRAY['Financial Services'], 'Investment Program', 'open', NULL, 'open', 'https://pif.gov.sa/en/pages/ventures/', 'Saudi Public Investment Fund (PIF) ventures and strategic investment program supporting companies aligned with Saudi Arabia''s Vision 2030 economic transformation agenda.', '2026-05-17'::date, 'Global'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://pif.gov.sa/en/pages/ventures/');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Saudi Energy Efficiency Center (SEEC) – Energy Efficiency Programs', 'Saudi Energy Efficiency Center (SEEC)', 'Saudi Arabia', ARRAY['Energy'], 'Program', 'open', NULL, 'open', 'https://www.seec.gov.sa/en/online-services/services', 'SEEC programs and services promoting energy efficiency across Saudi Arabia''s transport, industry, and buildings sectors, including licensing, Foras marketplace, and training.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://www.seec.gov.sa/en/online-services/services');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Saudi Heritage Commission – Heritage Sector Programs', 'Saudi Heritage Commission', 'Saudi Arabia', ARRAY['Tourism & Quality of Life'], 'Program', 'open', NULL, 'open', 'https://heritage.moc.gov.sa/en/', 'Saudi Heritage Commission programs supporting heritage preservation, cultural sites development, and heritage economy investment opportunities under the Ministry of Culture.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://heritage.moc.gov.sa/en/');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Saudi Heritage Commission – Research & Heritage Grants', 'Saudi Heritage Commission', 'Saudi Arabia', ARRAY['Tourism & Quality of Life'], 'Grant', 'open', NULL, 'open', 'https://heritage.moc.gov.sa/en/grants', 'Research and heritage grants from the Saudi Heritage Commission supporting projects related to archaeological, cultural, and intangible heritage preservation in Saudi Arabia.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://heritage.moc.gov.sa/en/grants');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'AWS Startups Program – Saudi Arabia', 'Amazon Web Services (AWS)', 'United States', ARRAY['ICT'], 'Startup Program', 'open', 'Up to $10,000 in AWS credits (KSA Founders Club); up to $100,000 for AWS Activate Portfolio tier', 'open', 'https://aws.amazon.com/startups/saudi-arabia/', 'AWS Startups program offering cloud credits, technical support, and go-to-market resources for Saudi Arabia-based startups, backed by $5B+ AWS investment in the Kingdom.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://aws.amazon.com/startups/saudi-arabia/');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Make it in the Emirates – Industrial Investment Forum', 'UAE Ministry of Industry and Advanced Technology (MoIAT)', 'United Arab Emirates', ARRAY['Industrial & Manufacturing'], 'Forum / Investment Platform', 'closed', NULL, 'closed', 'https://www.miite.ae/en', 'Annual UAE industrial investment forum (2026 edition: May 4–7, Abu Dhabi) connecting manufacturers, investors, and government to accelerate industrial growth across the GCC.', '2026-05-17'::date, 'GCC / Global'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://www.miite.ae/en');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'LogiPoint – Jeddah Islamic Port Bonded & Re-export Zone Investment', 'LogiPoint (Saudi Trade and Export Development Company)', 'Saudi Arabia', ARRAY['Transport & Logistics'], 'Investment Incentive', 'open', NULL, 'open', 'https://logipoint.sa/en/', 'LogiPoint operates the bonded and re-export free zone at Jeddah Islamic Port, offering manufacturers and traders duty-free trade benefits and logistical support for exports.', '2026-05-17'::date, 'Global'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://logipoint.sa/en/');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'National Technology Development Program (NTDP) – Technology Initiatives', 'National Technology Development Program (NTDP)', 'Saudi Arabia', ARRAY['ICT'], 'Program', 'open', NULL, 'open', 'https://www.ntdp.gov.sa/en/initiatives', 'NTDP initiatives supporting technology development, startup acceleration, and innovation in Saudi Arabia, including the AIM-X accelerator, Relocate program, and NEXT ERA initiative.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://www.ntdp.gov.sa/en/initiatives');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Ministry of Communications and IT (MCIT) – Digital Economy Initiatives', 'Ministry of Communications and Information Technology (MCIT)', 'Saudi Arabia', ARRAY['ICT'], 'Program', 'open', NULL, 'open', 'https://mcit.gov.sa/en/initiatives', 'Saudi MCIT digital economy initiatives covering cloud adoption, cybersecurity, digital transformation, and ICT sector development, with Saudi Arabia ranking #1 globally on the UN ICT Development Index.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://mcit.gov.sa/en/initiatives');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Riyadh Valley Company (RVC) – Innovation & Entrepreneurship Programs', 'Riyadh Valley Company (RVC)', 'Saudi Arabia', ARRAY['Innovation & Entrepreneurship'], 'Incubator / Venture Capital', 'open', NULL, 'open', 'https://rvc.com.sa/programs', 'Riyadh Valley Company (King Saud University''s investment arm) programs supporting technology startups through incubation, venture capital, and the KSU Venture Fund partnership with SparkLabs.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://rvc.com.sa/programs');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Cultural Development Fund (CDF) – Cultural Sector Financing Programs', 'Cultural Development Fund (CDF)', 'Saudi Arabia', ARRAY['Tourism & Quality of Life'], 'Financing Program', 'open', NULL, 'open', 'https://www.cdf.gov.sa/en/programs', 'Saudi Cultural Development Fund financing programs offering credit facilities and financial products to cultural entrepreneurs, artists, and creative economy businesses (SAR 3B+ suite launched 2025).', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://www.cdf.gov.sa/en/programs');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Qatar Financial Centre (QFC) – FinTech Sector Initiatives', 'Qatar Financial Centre (QFC)', 'Qatar', ARRAY['Financial Services'], 'Program', 'open', NULL, 'open', 'https://qfc.qa/en/industry-sectors/fintech', 'Qatar Financial Centre FinTech sector programs supporting fintech companies with licensing, regulatory support, and market access across the GCC and international financial markets.', '2026-05-17'::date, 'GCC / Global'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://qfc.qa/en/industry-sectors/fintech');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'SEEC Government Entities Energy Empowerment Program', 'Saudi Energy Efficiency Center (SEEC)', 'Saudi Arabia', ARRAY['Energy'], 'Regulatory Service', 'open', NULL, 'open', 'https://www.seec.gov.sa/en/online-services/12', 'SEEC regulatory service empowering Saudi government entities to submit energy consumption reports and implement efficiency measures per royal orders for national conservation targets.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://www.seec.gov.sa/en/online-services/12');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'Ministry of Industry and Mineral Resources – Standard Incentives for the Industrial Sector', 'Ministry of Industry and Mineral Resources (MIMR)', 'Saudi Arabia', ARRAY['Industrial & Manufacturing'], 'Investment Incentive', 'open', 'Up to 35% of initial project investment, capped at SAR 50 million', 'open', 'https://industry.sa/en/services/', 'Saudi MIMR Standard Incentives for the Industrial Sector providing up to 35% of initial investment (capped at SAR 50M) for licensed industrial facilities in the Kingdom.', '2026-05-17'::date, 'Global'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://industry.sa/en/services/');

INSERT INTO opportunities (id, title, sponsor_institution, country, sectors, type, status, funding_amount, deadline_date, application_link, description_short, last_verified, eligibility_region)
SELECT gen_random_uuid()::text, 'King Saud bin Abdulaziz University for Health Sciences – Research & Innovation', 'King Saud bin Abdulaziz University for Health Sciences (KSAU-HS)', 'Saudi Arabia', ARRAY['Healthcare & Life Sciences'], 'Research Grant', 'open', NULL, 'open', 'https://ksau-hs.edu.sa/English', 'Research and innovation programs at KSAU-HS including KAIMRC Healthy Longevity Research Grants, supporting healthcare research, clinical trials, and medical innovation in Saudi Arabia.', '2026-05-17'::date, 'Saudi Arabia'
WHERE NOT EXISTS (SELECT 1 FROM opportunities WHERE application_link = 'https://ksau-hs.edu.sa/English');